Appended the new versions to the User-Agent Header
akamai/AkamaiOPEN-edgegrid-php-client pull request #31
Opened 2019-02-15 18:21 UTC by gfirem

2019-02-28 19:24 UTC, dshafik requested changes

2019-02-28 19:24 UTC, dshafik commented on src/Client.php
> +	    if ( isset( $_ENV['AKAMAI_CLI'] ) && isset( $_ENV['AKAMAI_CLI_VERSION'] ) ) {
The spacing on the `if` is not PSR-1/2 compliant (looks like you followed WordPress style).

2019-02-28 19:24 UTC, dshafik commented on src/Client.php
> +	    if ( isset( $_ENV['AKAMAI_CLI_COMMAND'] ) && isset( $_ENV['AKAMAI_CLI_COMMAND_VERSION'] ) ) {
same here

2019-03-01 18:38 UTC, gfirem commented on src/Client.php
> +	    if ( isset( $_ENV['AKAMAI_CLI'] ) && isset( $_ENV['AKAMAI_CLI_VERSION'] ) ) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2023-09-15 08:14 UTC, closed without merging